### ISSUE TITLE
Failed download from PhyloPic.org

### ISSUE THREAD

**Issue by Marina0729** [YuLab-SMU/treedata-book#1]
Dear Dr.Yu
I am using your wonderful tree-book to create a figure for a paper. I look forward to your response to this question. 

#Question:
I received a Warning message when I tried to retrieve PhyloPics from the database. 

**Error in download_url(path) : 
  Failed to download http://phylopic.org/assets/images/submissions/7e9286b9-0e49-46c2-88f6-218291fb06a4.512.png (HTTP 404)**

I used the code below:

`newick <- "(Homo_sapiens:0.029752,(((Xenopus_tropicalis:0.096645,Caenorhabditis_elegans:0.647764):0.030884,Danio_rerio:0.100106):0.064097,Gallus_gallus:0.029353):0.024960,Mus_musculus:0.018171);"`

`tree <- read.tree(text=newick)`

`d <- ggimage::phylopic_uid(tree$tip.label)`

`ggtree(tree) %<+% d +
  geom_tiplab(aes(image=uid), geom="phylopic", offset=2.5) +
  geom_tiplab(aes(label=label), offset = .2) + xlim(NA, 7) +
  scale_color_viridis_d()`

**Comment by GuangchuangYu** [comment]
indeed, the image, <http://phylopic.org/assets/images/submissions/7e9286b9-0e49-46c2-88f6-218291fb06a4.512.png> is not exists. However, the ID is correct and the image <<http://phylopic.org/assets/images/submissions/7e9286b9-0e49-46c2-88f6-218291fb06a4.256.png> do exists.

Now, if you install github version of `ggimage` (>=0.2.6), your script will work as I set the default width to 256, instead of 512.

Users can set the width manually via  e.g. `options(phylopic_width=512)`.
